#!/bin/sh
root=`pwd`/mnt

mounted=false
if ! findmnt "$root"; then
	./root-mount || { echo "ERROR: mount"; exit 1; }
	mounted=true
fi

#ZYPP_CONF=/local/dsterba/vm-qemu-vm5
#sudo -E

sudo mount --bind /dev mnt/dev
sudo mount --bind /proc mnt/proc
sudo mount --bind /sys mnt/sys

sudo zypper --root "$root" -v sh

sudo umount mnt/dev mnt/proc mnt/sys

if $mounted; then ./root-umount; fi
