#!/bin/sh

# reset autorun or set to a specific script
# usage: $0 [script]
#
# the script will be placed to the root

./root-mount || { echo "ERROR: no mount"; exit 1; }

if [ -z "$1" ]; then
	p=$(readlink /autorun.sh 2>/dev/null)
	echo "Clear autorun.sh (current: $p)"
	sudo rm -vf mnt/autorun.sh
else
	if ! [ -f "$1" ]; then
		echo "ERROR: autorun script not found"
	else
		echo "Set autorun to: $1"
		sudo ln -sf "/$1" mnt/autorun.sh
	fi
fi

./root-umount
