#!/usr/bin/sh

# 0 | 2
# -----
# 1
layout1() {
	tmux splitw -t 0   -d -v -l 30% './serial-start'
	tmux splitw -t 0   -d -h -l 50% './tail-log'
}

# 0 | 1
# 2 |
layout2() {
	tmux splitw -t 0   -d -h -l 50% './tail-log'
	tmux splitw -t 0   -d -v -l 70% './serial-start'
}

layout2
